### ISSUE TITLE
Two errors in _mm256_movemask_epi8_dbg()

### ISSUE THREAD

**Issue by rosbif** [emea-ssg-drd/Immintrin-debug#10]
a_vec[32] should be uint8_t not uint32_t.
dst should be initialized to zero.

**Comment by izard** [comment]
Thank you very much! This is the most worrying so far: all previous bugs you've reported are clearly my fault as they are all in hand-written code, and this one is in generated code, I don't know how my parser/generator could have emitted that. I don't have access to the parser so fixed in place.

**Comment by izard** [comment]
somehow can't commit, looks like GitHub network issue. will re-try in an hour
