### ISSUE TITLE
GCC compilation warning "warning: bitwise comparison always evaluates to false"

### ISSUE THREAD

**Issue by imaginary-person** [emea-ssg-drd/Immintrin-debug#12]
Hello @Zvictoria,

I get lots of compilation warnings while trying to use `immintrin_dbg.h`:

```
immintrin_dbg.h:59979:40: warning: bitwise comparison always evaluates to false [-Wtautological-compare]
59979 |   if ((imm8 & ((1 << 1) & 0xffffffff)) == 1) {

```

Please let me know if this warning is expected (nothing to worry about).
Thank you!

**Comment by Zvictoria** [comment]
Hi, @imaginary-person . Thanks for reporting a bug. It is is real, not imaginary :) We need to do something like  if ((imm8 & 0xA) == 1) {  
Need to talk to the repo owner on its fix. @izard - are you still here?

**Comment by izard** [comment]
Great catch, will fix later today/PST time. Thanks a lot!

**Comment by imaginary-person** [comment]
Thanks a lot for your help, @izard & @Zvictoria!
