### ISSUE TITLE
Missing intrinsics mostly in AVX/EPI domain

### ISSUE THREAD

**Issue by hfp** [emea-ssg-drd/Immintrin-debug#2]
First of all - Thank you for this project!

I found the following intrinsics missing (likely more from the AVX/EPI domain):

* _mm512_undefined_epi32
* _mm256_movemask_epi8
* _mm512_srli_epi32
* _mm512_slli_epi32
* _mm512_xor_epi32
* _mm512_or_epi32

How to (not) reproduce:

* Git-clone the master revision of LIBXSMM: `git clone https://github.com/hfp/libxsmm.git`
* Copy `immintrin_dbg.h` to include directory: `cp immintrin_dbg.h /path/to/libxsmm/include`
* Edit https://github.com/hfp/libxsmm/blob/master/include/libxsmm_intrinsics_x86.h#L37 (0 -> 1)
* Build LIBXSMM: `cd /path/to/libxsmm; make`

Actually, this issue cannot be reproduced as shown above because there workarounds in place for all missing intrinsics.

**Comment by izard** [comment]
Hello Hans, thank you for the report, will fix shortly.
