### ISSUE TITLE
Out of bounds accesses

### ISSUE THREAD

**Issue by rosbif** [emea-ssg-drd/Immintrin-debug#6]
I get an enormous quantity of compiler warnings, some of which seem very serious.
For instance in _mm_cvt_roundss_sd_dbg() and the following functions there are clearly out of bounds accesses to dst_vec[] and a_vec[].

**Comment by izard** [comment]
Thank you very much, I fixed 6 functions affected. I no longer work at Intel so won't have time for all the warnings :(
